### ISSUE TITLE
收不到网关服务器的响应

### ISSUE THREAD

**Issue by pretendb** [ArthasModern/AlipayOpenapiCpp#2]
![image](https://cloud.githubusercontent.com/assets/16880824/21671479/9ff87d8c-d356-11e6-93b6-2c9f13e10173.png)
上面是使用c语言版的sdk，在沙箱环境的调试结果，可以顺利获得响应

![image](https://cloud.githubusercontent.com/assets/16880824/21671512/d5e452b8-d356-11e6-9b05-fc99a6aa5e9a.png)
而使用c++版的sdk却无法获得网关服务器的响应，请问您碰到过这个坑吗？

**Comment by lemonc2009** [comment]
我现在是能收到响应，但是验签不通过，能否交流一下？
lemonc2009@gmail.com 3x
