### ISSUE TITLE
Qt 5.11.1 下使用 MinGW 编译，提示很多 undefine

### ISSUE THREAD

**Issue by Mtr1994** [ArthasModern/AlipayOpenapiCpp#9]
我这儿是库的位数不对嘛？老哥，这个多少位的库 ？

**Comment by mxj12345** [comment]
32位的,我也出现了很多问题,什么无法解析的外部符号,库计算机类型“x86”与目标计算机类型“x64”冲突等等,你解决了吗?

**Comment by Dump1ings** [comment]
> 我这儿是库的位数不对嘛？老哥，这个多少位的库 ？

32位的,我也出现了很多问题,什么无法解析的外部符号,库计算机类型“x86”与目标计算机类型“x64”冲突等等,你解决了吗?

**Comment by Mtr1994** [comment]
> > 我这儿是库的位数不对嘛？老哥，这个多少位的库 ？
> 
> 32位的,我也出现了很多问题,什么无法解析的外部符号,库计算机类型“x86”与目标计算机类型“x64”冲突等等,你解决了吗?

搞定了，这个库是可以用的，我这边使用的是二维码扫码付钱，已经完成了，里面有些东西不能用，它的业务层的东西不要用，只用底层的东西就行了，整个工程我这儿也无法编译 ~

**Comment by ArthasModern** [comment]
C++的类库的问题，建议根据自己的编译环境，自行编译一个可用的版本，可能的差异有32位/64位、arm/x86、linux/window等等，所以这里无法提供所有环境下的类库
